<?php 
	
	/*前台路由*/
	Route::group(['middleware'=>['web','api'],'prefix'=>'api'],function(){
		/*密码登录*/
		Route::post('/loginByPassword','Readingbar\Api\Frontend\Controllers\LoginController@loginByPassword');
		/*消息验证登录*/
		Route::post('/loginByCode','Readingbar\Api\Frontend\Controllers\LoginController@loginByCode');
		/*登出*/
		Route::get('/logout','Readingbar\Api\Frontend\Controllers\LoginController@logout');
		/*注册*/
		Route::post('/register','Readingbar\Api\Frontend\Controllers\RegisterController@register');
		/*忘记密码-重置密码*/
		Route::post('/forgoten','Readingbar\Api\Frontend\Controllers\ForgotenController@forgoten');
		/*发送验证消息*/
		Route::group(['prefix'=>'message'],function(){
			/*发送登录验证消息*/
			Route::get('/sendLoginCode','Readingbar\Api\Frontend\Controllers\MessageController@sendLoginCode');
			/*发送邮箱验证消息*/
			Route::get('/sendEmailCode','Readingbar\Api\Frontend\Controllers\MessageController@sendEmailCode');
			/*发送手机验证消息*/
			Route::get('/sendMobileCode','Readingbar\Api\Frontend\Controllers\MessageController@sendMobileCode');
			/*发送注册验证消息*/
			Route::post('/sendCodeForRegister','Readingbar\Api\Frontend\Controllers\MessageController@sendRegisterCode');
			/*发送重置密码验证消息*/
			Route::get('/sendForgotenCode','Readingbar\Api\Frontend\Controllers\MessageController@sendForgotenCode');
		});
		/*会员api路由*/
		Route::group(['middleware'=>['member'],'prefix'=>'member'],function(){
			/*数据*/
			Route::get('/baseinfo','Readingbar\Api\Frontend\Controllers\MemberController@baseinfo');
			/*操作*/
			/*修改基础信息*/
			Route::post('/modify/baseinfo','Readingbar\Api\Frontend\Controllers\MemberController@modifyBaseinfo');
			/*修改邮箱*/
			Route::post('/modify/email','Readingbar\Api\Frontend\Controllers\MemberController@modifyEmail');
			/*修改手机*/
			Route::post('/modify/mobile','Readingbar\Api\Frontend\Controllers\MemberController@modifyMobile');
			/*修改安全问题*/
			Route::post('/modify/aq','Readingbar\Api\Frontend\Controllers\MemberController@modifyAq');
			/*修改密码*/
			Route::post('/modify/password','Readingbar\Api\Frontend\Controllers\MemberController@modifyPassword');
			/*修改头像*/
			Route::post('/modify/avatar','Readingbar\Api\Frontend\Controllers\MemberController@modifyAvatar');
			/*会员消息*/
			Route::group(['prefix'=>'message'],function(){
				/*会员消息列表*/
				Route::get('/','Readingbar\Api\Frontend\Controllers\MessageController@getMessagesByMember');
				/*消息详情*/
				Route::get('/detail/{reply}','Readingbar\Api\Frontend\Controllers\MessageController@getMessageDetail');
				/*回复消息*/
				Route::get('/reply','Readingbar\Api\Frontend\Controllers\MessageController@replyToPreId');
				/*删除消息*/
				Route::get('/delete','Readingbar\Api\Frontend\Controllers\MessageController@deleteMessage');
				/*发送消息给老师*/
				Route::get('/send','Readingbar\Api\Frontend\Controllers\MessageController@sendMessageToTeacher');
			});
			/*老师*/
			Route::group(['prefix'=>'teachers'],function(){
				/*获取所有关联老师*/
				Route::get('/all','Readingbar\Api\Frontend\Controllers\TeacherController@all');
			});
			/*孩子*/
			Route::group(['prefix'=>'children'],function(){
				/*获取孩子信息*/
				Route::get('/all','Readingbar\Api\Frontend\Controllers\ChildrenController@all');
				/*根据编号获取孩子信息*/
				Route::get('/childById','Readingbar\Api\Frontend\Controllers\ChildrenController@childById');
				/*新增孩子信息*/
				Route::post('/newChild','Readingbar\Api\Frontend\Controllers\ChildrenController@newChild');
				/*修改孩子信息*/
				Route::post('/modifyChild','Readingbar\Api\Frontend\Controllers\ChildrenController@modifyChild');
				/*删除孩子信息*/
				Route::post('/deleteChild','Readingbar\Api\Frontend\Controllers\ChildrenController@deleteChild');
				/*基础调查*/
				Route::group(['prefix'=>'survey'],function(){
					/*获取调查的内容*/
					Route::get('/getSurvey','Readingbar\Api\Frontend\Controllers\SurveyController@getSurvey');
					/*提交调查表单*/
					Route::post('/submitSurvey','Readingbar\Api\Frontend\Controllers\SurveyController@submitSurvey');
				});
				/*star评测*/
				Route::group(['prefix'=>'star'],function(){
					/*star评测申请*/
					Route::post('/apply','Readingbar\Api\Frontend\Controllers\StarController@starApply');
					/*获取star评测账号*/
					Route::get('/account','Readingbar\Api\Frontend\Controllers\StarController@starAccount');
					/*获取star评测结果*/
					Route::get('/report','Readingbar\Api\Frontend\Controllers\StarController@starReport');
					/*查看star报告*/
					Route::get('/readReport/{student_id}/{report_id}/{type}','Readingbar\Api\Frontend\Controllers\StarController@readReport');
				});
				/*阅读计划*/
				Route::group(['prefix'=>'readplan'],function(){
					/*获取阅读计划*/
					Route::get('/plans','Readingbar\Api\Frontend\Controllers\ReadPlanController@plans');
					/*同意阅读计划*/
					Route::get('/agree','Readingbar\Api\Frontend\Controllers\ReadPlanController@agreePlan');
					/*不同意阅读计划*/
					Route::get('/unagree','Readingbar\Api\Frontend\Controllers\ReadPlanController@unagreePlan');
					/*申请阅读计划*/
					Route::get('/apply','Readingbar\Api\Frontend\Controllers\ReadPlanController@applyReadPlan');
					/*还书*/
					Route::get('/return','Readingbar\Api\Frontend\Controllers\ReadPlanController@returnBooks');
				});
				/*书籍*/
				Route::group(['prefix'=>'book'],function(){
					/*获取孩子的书籍评论*/
					Route::get('/getCommentOfChild','Readingbar\Api\Frontend\Controllers\BookController@getCommentOfChild');
					/*孩子评论书籍*/
					Route::post('/commentForBook','Readingbar\Api\Frontend\Controllers\BookController@commentForBook');
				});
			});
			
			/*获取当前用户的优惠券*/
			Route::group(['prefix'=>'discount'],function(){
				Route::get('/getDiscounts','Readingbar\Api\Frontend\Controllers\Discount\DiscountController@getDiscounts');
			});
			
			/*推广*/
			Route::group(['prefix'=>'promotions'],function(){
				/*推广查询-会员信息*/
				Route::get('/getMembers','Readingbar\Api\Frontend\Controllers\Promotions\PromotionsController@getMembers');
				/*推广查询-订单信息*/
				Route::get('/getMOrders','Readingbar\Api\Frontend\Controllers\Promotions\PromotionsController@getMOrders');
				/*推广查询-面板数据*/
				Route::get('/getDashboard','Readingbar\Api\Frontend\Controllers\Promotions\PromotionsController@getDashboard');
			});
			/*订单*/
			Route::group(['prefix'=>'giftCard'],function(){
				/*获取用户订单*/
				Route::post('/activeCard','Readingbar\Api\Frontend\Controllers\GiftCard\GiftCardController@activeCard');
			});
			/*订单*/
			Route::group(['prefix'=>'order'],function(){
				/*获取用户订单*/
				Route::get('/all','Readingbar\Api\Frontend\Controllers\OrderController@getOrders');
				/*根据订单号查询订单状态*/
				Route::get('/getStatusByOID','Readingbar\Api\Frontend\Controllers\OrderController@getStatusByOID');
				/*微信支付jsapi支付调用*/
				Route::get('/wxpayJsapi','Readingbar\Api\Frontend\Controllers\OrderController@wxpayJsapi');
				/*续费*/
				Route::post('/renew','Readingbar\Api\Frontend\Controllers\OrderController@renew');
				/*创建订单*/
				Route::post('/create','Readingbar\Api\Frontend\Controllers\OrderController@createOrder');
				/*支付未付款订单*/
				Route::post('/pay','Readingbar\Api\Frontend\Controllers\OrderController@payOrder');
				/*删除未付款订单*/
				Route::post('/delete','Readingbar\Api\Frontend\Controllers\OrderController@deleteOrder');
			});
		});
		Route::get('/notice','Readingbar\Api\Frontend\Controllers\Notice\NoticeController@getNotices');
		/*文章*/
		Route::group(['prefix'=>'article'],function(){
			Route::get('/getWxArticlesList','Readingbar\Api\Frontend\Controllers\Article\ArticleController@getWxArticlesList');
		});
		
	});
	Route::group(['middleware'=>['access_log'],'prefix'=>'api'],function(){
		/*订单*/
		Route::group(['prefix'=>'order'],function(){
			/*支付宝同步通知&异步通知*/
			Route::post('/alipayNotifyUrl','Readingbar\Api\Frontend\Controllers\OrderController@alipayNotifyUrl');
			/*微信支付通知*/
			Route::post('/wxpayNotifyUrl','Readingbar\Api\Frontend\Controllers\OrderController@wxpayNotifyUrl');
		});
	});
	Route::group(['middleware'=>['web','access_log'],'prefix'=>'api'],function(){
		/*支付宝同步通知&异步通知*/
		Route::get('/alipayReturnUrl','Readingbar\Api\Frontend\Controllers\OrderController@alipayReturnUrl');
		/*微信支付通知*/
		Route::get('/wxpay','Readingbar\Api\Frontend\Controllers\OrderController@wxpay');
	});
?>